openapi: 3.0.4
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a Torang Server based on the OpenAPI 3.0 specification.
  version: 1.0.12

servers:
  # - url: http://sarang628.iptime.org:8081
  - url: http://localhost:8081

tags:
  - name: feed
    description: Feed API

paths:
  "/feed/v1/page/{page}/size/{size}":
    get:
      tags:
        - feed
      summary: Get paged feed list
      operationId: getFeedPage
      parameters:
        - name: page
          in: path
          required: true
          schema:
            type: integer
            example : 0
        - name: size
          in: path
          required: true
          schema:
            type: integer
            example : 20
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FeedResponseModel'

      security:
        - bearerAuth: []
  "/feed/v1/favorite":
    get:
      responses:
      '200':
        description: successful operation

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    FeedResponseModel:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string