openapi: 3.0.4
info:
  title: 토랑(Torang) API
  description: |-
    This is a Torang API allows you to get Application data.
  version: 1.0.0

servers:
  - url: http://sarang628.iptime.org:8081
  - url: http://localhost:8081

tags:
  - name: feed
    description: Feed API

paths:
  "/feed/v1/page/{page}/size/{size}":
    get:
      tags:
        - feed
      summary: Get paged feed list
      operationId: getFeedPage
      parameters:
        - name: page
          in: path
          required: true
          schema:
            type: integer
            example : 0
        - name: size
          in: path
          required: true
          schema:
            type: integer
            example : 20
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FeedResponseModel'

      security:
        - bearerAuth: []
  "/feed/v1/favorite":
    get:
      tags:
        - favorite
      security:
        - bearerAuth: []
      description: Get favorite feed
      responses:
        '200':
          description: OK
        '405':
          description: FAILED
  "/feed/v1/like":
    get:
      tags:
        - like
      security:
        - bearerAuth: []
      description: Get favorite feed
      responses:
        '200':
          description: OK
        '405':
          description: FAILED
  "/emailLoginPlain":
    post:
      tags:
        - login
      parameters:
        - in: query
          name: email
          required: true
          schema:
            type: string
            example : sry_ang@naver.com
        - in: query
          name: password
          required: true
          schema:
            type: string
            example : Torang!234
      responses:
        '200':
          description: OK
  "/feed/v1/feedGrid/{reviewId}/offset/{offset}":
    get:
      tags:
        - feed
      parameters:
        - name : reviewId
          in: path
          schema:
            type: integer
            example : 631
          required: true
        - name : offset
          in: path
          schema:
            type: integer
            example : 20
          required: true
      responses:
        '200':
          description: successful operation
  "/api/menu/{restaurantId}":
    get:
      tags:
        - menu
      parameters:
        - name: restaurantId
          in: path
          schema:
            type: integer
            example: 234
          required: true
      responses:
        '200':
          description: successful operation
  "/api/menu/v1/{restaurantId}":
    get:
      tags:
        - menu
      summary: Finds Menus by RestaurantId
      parameters:
        - name: restaurantId
          in: path
          schema:
            type: integer
            example: 362
          required: true
      responses:
        '200':
          description: successful operation


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    FeedResponseModel:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string